motor_controller:
  ros__parameters:
    points:
      # (row, col): label, x, y
      # label = [Home, Valid, Invalid]
      0,0: Home, -0.05, 0.0;
      1,0: Valid, 0.3, 0.0;
      2,0: Valid, 0.75, 0.0;
      3,0: Valid, 1.2, 0.0;
      4,0: Valid, 1.75, 0.0;
      0,1: Valid, -0.05, 0.6;
      1,1: Valid, 0.3, 0.45;
      2,1: Valid, 0.75, 0.45;
      3,1: Valid, 1.2, 0.45;
      4,1: Valid, 1.75, 0.3;
      0,2: Valid, -0.05, 0.725;
      1,2: Valid, 0.3, 0.725;
      2,2: Valid, 0.75, 0.725;
      3,2: Valid, 1.2, 0.725;
      4,2: Valid, 1.75, 0.725;
      0,3: Valid, -0.05, 1.27;
      1,3: Valid, 0.3, 1.27;
      2,3: Valid, 0.75, 1.27;
      3,3: Valid, 1.2, 1.27;
      4,3: Valid, 1.75, 1.27;
      0,4: Valid, -0.05, 1.6;
      1,4: Valid, 0.3, 1.42;
      2,4: Valid, 0.75, 1.42;
      3,4: Valid, 1.2, 1.42;
      4,4: Valid, 1.75, 1.42;
      0,5: Valid, -0.05, 1.65;
      1,5: Valid, 0.3, 1.65;
      2,5: Valid, 0.75, 1.65;
      3,5: Valid, 1.2, 1.65;
      4,5: Valid, 1.75, 1.7;
      0,6: Valid, -0.05, 2.175;
      1,6: Valid, 0.3, 2.175;
      2,6: Valid, 0.75, 2.175;
      3,6: Valid, 1.2, 2.175;
      4,6: Valid, 1.75, 2.175;
      0,7: Valid, -0.05, 2.6;
      1,7: Valid, 0.3, 2.6;
      2,7: Valid, 0.75, 2.6;
      3,7: Valid, 1.2, 2.6;
      4,7: Valid, 1.75, 2.6;
      0,8: Valid, -0.05, 2.9;
      1,8: Valid, 0.3, 2.9;
      2,8: Valid, 0.75, 2.9;
      3,8: Valid, 1.2, 2.9;
      4,8: Valid, 1.75, 2.9;

